export const ActionTypes = {
  FETCH_STAYS: "FETCH_STAYS",
  SET_STAYS: "SET_STAYS",
  STAY_CLICK: " STAY_CLICK",
  ROLE: "ROLE",
  SIGNUP_CLICK: "SIGNUP_CLICK",
  SIGNIN_CLICK: "SIGNIN_CLICK",
  POST_CLICK: "POST_CLICK",
};
