export const ActionTypes = {
  FETCH_STAYS: "FETCH_STAYS",
  SET_STAYS: "SET_STAYS",
  HOUSE_CLICK: "HOUSE_CLICK",
  PG_CLICK: "PG_CLICK",
  ROLE: "ROLE",
  SIGNUP_CLICK: "SIGNUP_CLICK",
  SIGNIN_CLICK: "SIGNIN_CLICK",
  OWNER_NAME: "OWNER_NAME",
  USER_NAME: "USER_NAME",
  POST_CLICK: "POST_CLICK",
  SIGNUP_USER_VALUES: "SIGNUP_USER_VALUES",
  SIGNUP_OWNER_VALUES: "SIGNUP_OWNER_VALUES",
};
